# This is a Secret resource. Secrets let you store and manage sensitive information, such as passwords, OAuth tokens, and ssh keys.

# The apiVersion defines the versioned schema of this representation of an object.
apiVersion: v1

# The kind is a string value representing the REST resource this object represents.
kind: Secret

# Standard object's metadata.
metadata:
  # Name of the Secret, must be unique.
  name: simplecrud-secret

# The type of the secret. "Opaque" is used for arbitrary user-defined data.
type: Opaque

# Data contains the secret data. Each key-value pair in the data field of the Secret corresponds to a secret property.
data:
  # The key is the secret property name and the value is its value. The value must be base64-encoded.
  PORT: 8020